on:
  push:
    branches:
      - master
  release:
    types:
      - created

name: Deploy
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: make install_ubuntu tes
        run: make install_ubuntu tes
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}